language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "10"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

sudo: false

after_success:
 - if [[ ${TRAVIS_NODE_VERSION} == "10" ]]; then npm run coverage; fi;
